### ISSUE TITLE
Update User Interface of clothing.html

### ISSUE THREAD

**Issue by seiay** [supersaintex/saint-sorting#18]
The current user interface of the clothing page is not good.
So we should change color and update the design by editing clothing.css.

**Comment by seiay** [comment]
Is not the changed clothing,css reflected?

**Comment by seiay** [comment]
We can use update the design by using [Bootstrap](https://getbootstrap.jp/).

**Comment by asana17** [comment]
> Is not the changed clothing,css reflected?

This may be caused by the browser cache. Opening the chrome Developer tool and clicking the reload icon with the right mouse button, you can see `Empty Cache and Hard Reload`. You can refresh cash by this command temporarily.

**Comment by seiay** [comment]
> Opening the chrome Developer tool and clicking the reload icon with the right mouse button, you can see Empty Cache and Hard Reload. 

Thanks!
I can reflect CSS file by this way.
