### ISSUE TITLE
add application test

### ISSUE THREAD

**Issue by asana17** [supersaintex/saint-sorting#21]
add test for our application

**Comment by seiay** [comment]
## 実装方針(3/9 meeting)
1. cargo testでできるかやってみる

2-1. 別のcrateを作り、そこでthirtyfourの例のように、別のwebサーバーを立てる。
（微妙？）
2-2. 別のクレートを作るくらいなら、別の言語（JavaScript, Python）で実装する。

1ができなさそうだとわかれば、2のうちどちらでやるか相談する。

**Comment by seiay** [comment]
cargo testによって、thirtyfourのexampleの実行（wikioediaのページを表示させるところまで）を確認した。
