### ISSUE TITLE
install thirtyfour and java to run selenium

### ISSUE THREAD

**Issue by Kai-Kuze** [supersaintex/saint-sorting#39]
I have finished installing selenium, chrome_driver and java.

**Comment by Kai-Kuze** [comment]
but when I ran "java -jar selenium-server-4.8.1.jar --ext example.jar:dir standalone" on zsh, Zsh returned "Error: Unable to access jarfile selenium-server-4.8.1.jar".

**Comment by asana17** [comment]
Please give us more info. When you ask a question about installation or building, you should tell us about environmental information and installation/building steps.
Also, asking questions not related to our application here is not recommended. The problem of Java and Selenium installation has no relationship to this application.
